/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : RTF2TEXT
 #	author : miyako
 #	2017/05/30
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include "rtfconv.h"
#endif

// --- RTF2TEXT
void RTF_to_text(sLONG_PTR *pResult, PackagePtr pParams);
